### ISSUE TITLE
Weird Errors when building 0.1.5 with Surreal 1.0.0

### ISSUE THREAD

**Issue by Pulsar-Programmer** [ixhbinphoenix/actix-session-surrealdb#4]
I'm getting unexpected errors when building actix-session-surrealdb on version 0.1.5. Could it be that I am using SurrealDB 1.0.0 and the version had some breaking changes? 
Here are the compile errors I am getting below:

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:158:32
    |
158 | ..._: KeyRecord = self.client.delete(thingy).await.expect("Deleting database record failed!...
    |       ---------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `KeyRecord`, found `Option<_>`
    |       |
    |       expected due to this
    |
    = note: expected struct `KeyRecord`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:177:56
    |
177 |           let res: Result<KeyRecord, surrealdb::Error> = self
    |  ________________________________________________________^
178 | |             .client
179 | |             .create(self.tb.clone())
180 | |             .content(KeyRecord {
...   |
187 | |             })
188 | |             .await;
    | |__________________^ expected `Result<KeyRecord, ...>`, found `Result<Vec<_>, Error>`
    |
    = note: expected enum `Result<KeyRecord, _>`
               found enum `Result<Vec<_>, _>`

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:220:56
    |
220 | ...::Error> = self.client.update(thingy).merge(updated).await;
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<KeyRecord, ...>`, found `Result<Option<...>, ...>`
    |
    = note: expected enum `Result<KeyRecord, _>`
               found enum `Result<std::option::Option<_>, _>`

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:237:13
    |
237 | ...   self.client.delete(thingy).await.map_err(|_| anyhow!("Failed to delete database record"))
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(), Error>`, found `Result<Option<...>, ...>`
    |
    = note: expected enum `Result<(), _>`
               found enum `Result<std::option::Option<_>, _>`
note: return type inferred to be `Result<(), anyhow::Error>` here
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:229:95
    |
229 |       async fn update_ttl(&self, session_key: &SessionKey, ttl: &Duration) -> Result<(), Error> {
    |  _______________________________________________________________________________________________^
230 | |         let id = session_key.as_ref().to_owned();
231 | |         let thingy = Thing {
232 | |             tb: self.tb.clone(),
...   |
252 | |         }
253 | |     }
    | |_____^

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:251:13
    |
251 | ...   self.client.update(thingy).merge(updated).await.map_err(|_| anyhow!("Failed to update database record"))
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(), Error>`, found `Result<Option<...>, ...>`
    |
    = note: expected enum `Result<(), _>`
               found enum `Result<std::option::Option<_>, _>`
note: return type inferred to be `Result<(), anyhow::Error>` here
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-session-surrealdb-0.1.5/src/lib.rs:229:95
    |
229 |       async fn update_ttl(&self, session_key: &SessionKey, ttl: &Duration) -> Result<(), Error> {
    |  _______________________________________________________________________________________________^
230 | |         let id = session_key.as_ref().to_owned();
231 | |         let thingy = Thing {
232 | |             tb: self.tb.clone(),
...   |
252 | |         }
253 | |     }
    | |_____^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `actix-session-surrealdb` (lib) due to 5 previous errors

**Comment by ixhbinphoenix** [comment]
Yes, there have been breaking changes in SurrealDB 1.0 that broke the library. I still need to work on this, fix will be done either today or on tuesday

**Comment by Pulsar-Programmer** [comment]
Oh, great! Thanks for letting me know! Take your time; no rush.

**Comment by ixhbinphoenix** [comment]
Should be fixed in 0.1.6
