### ISSUE TITLE
Actix-Session 0.7.2 -> 0.8.0 breaks SessionStore implementation for SurrealSessionStore

### ISSUE THREAD

**Issue by Pulsar-Programmer** [ixhbinphoenix/actix-session-surrealdb#5]
Hey, sorry, it's me again. I've been trying to use actix-session 0.8.0, and it seems as if another breaking change has occurred where the implementation for SessionStore has changed. I've checked the documentation for the trait before and after and cannot see any breaking changes or anything, but I'm not sure. I just know that this error goes away after downgrading to 0.7.2.
Sorry for bothering you, and no rush; I can just use actix-identity 0.7.2, but I just wanted to make you aware.

**Comment by ixhbinphoenix** [comment]
Seems to just be that the compiler doesn't allow the trait implementation of another version of actix-session, should be as easy as updating the lib. Update will be online in like 2 mins. Thank you for reporting this, I will be setting up dependabot now to catch this in the future.

**Comment by Lockroach** [comment]
W mans, thanks for helping out (I'm working with pulsar programmer)

**Comment by Pulsar-Programmer** [comment]
Yes, thank you so much! Sounds good!

**Comment by ixhbinphoenix** [comment]
Fix is now in version 0.1.7
